import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useSession } from 'next-auth/react';
import { Button, Paper, Skeleton, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';
import Nav from '../components/Nav';
import { useLeaderboard } from '../models/leaderboard/queries';

const Leaderboard: NextPage = () => {
  const session = useSession();
  const isAuthenticated = session && !!session.data?.address;

  const leaderboardQuery = useLeaderboard();

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {/* Navigation */}
        {isAuthenticated && <Nav />}

        <ConnectButton />

        {/* Display list of ERC20 tokens */}
        {isAuthenticated && (
          <Paper sx={{ padding: '1rem 1.5rem', marginTop: '2rem', minWidth: '700px' }}>
            <Typography variant="h5">Leaderboard</Typography>
            {/* Display loading state */}
            {leaderboardQuery.isLoading && (
              <div>
                <Skeleton height={52} variant="text" />
                <Skeleton height={52} variant="text" />
                <Skeleton height={52} variant="text" />
                <Skeleton height={52} variant="text" />
                <Skeleton height={52} variant="text" />
              </div>
            )}
            {/* Display error state */}
            {leaderboardQuery.isFetched && leaderboardQuery.isError && (
              <>
                <p>There was a problem while loading leaderboard.</p>
                <Button variant="contained" onClick={() => leaderboardQuery.refetch()}>
                  Retry
                </Button>
                <Typography variant="caption" display="block" gutterBottom mt="1.5rem">
                  Technical details: {leaderboardQuery.error.message}
                </Typography>
              </>
            )}
            {/* Display success state */}
            {leaderboardQuery.isFetched && leaderboardQuery.isSuccess && (
              <Table sx={{ minWidth: 650 }} aria-label="simple table">
                <TableHead>
                  <TableRow>
                    <TableCell>Wallet address</TableCell>
                    <TableCell align="right">Score</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {leaderboardQuery.data.map((entry) => (
                    <TableRow key={entry.address}>
                      <TableCell> {entry.address} </TableCell>
                      <TableCell align="right"> {entry.score.toFixed(0)} </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </Paper>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Leaderboard;
